services:
  app:
    container_name: training-app-container
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${API_WEB_SERVER_PORT}:${API_WEB_SERVER_PORT}
    environment:
      API_WEB_SERVER_PORT: ${API_WEB_SERVER_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - network
  telegram:
    container_name: training-telegram-container
    build:
      context: .
      dockerfile: cmd/telegram/Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${TELEGRAM_WEB_SERVER_PORT}:${TELEGRAM_WEB_SERVER_PORT}
    environment:
      TELEGRAM_WEB_SERVER_PORT: ${TELEGRAM_WEB_SERVER_PORT}
    depends_on:
      app:
        condition: service_started
    networks:
      - network
  database:
    container_name: training-db-container
    image: postgres:16-bullseye
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    volumes:
      - ./data/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}'"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - network

networks:
  network:
