# File for client navigation
# Used in telegram application, can be used in other clients in future (whatsapp and etc)
client_navigation_tree:
  name: "Main Menu"
  sections:
    - id: "start_training"
      name: "Начать тренировку"
      description: "Старт цикла тренировок, аналитика пока в процессе для этого раздела"

    - id: "settings"
      description: "Настройки пользователя, где он может настроить тренировки, упражнения - либо полностью задать свои, либо выбрать готовые пресеты тренировок, упражнений"
      sections:
        - id: "schedule"
          description: "Расписание тренировок пользователя"
        - id: "training"
          description: "Раздел для редактирования тренировок пользователя"
        - id: "exercise"
          description: "Раздел для редактирования упражнений пользователя"

    - id: "admin"
      description: "Админка основная для общих данных"
      sections:
        - id: "training"
          description: "Раздел для редактирования готовых тренировок"
        - id: "exercise"
          description: "Раздел для редактирования готовых упражнений"
        - id: "machine"
          description: "Раздел для редактирования тренажеров"
          warning: "(!) Данный раздел заполняется только в админке для общих данных, для добавления нового тренажера пожалуйста обратитесь к автору бота"
        - id: "muscle_group"
          description: "Раздел для редактирования групп мышц"
          warning: "(!) Данный раздел заполняется только в админке для общих данных, для добавления новой (группы мышц/мышцы) пожалуйста обратитесь к автору бота"
        - id: "muscle"
          description: "Раздел для редактирования мышц"
          warning: "(!) Данный раздел заполняется только в админке для общих данных, для добавления новой мышцы пожалуйста обратитесь к автору бота"
